version: '3.9'

networks:
  dbTestNet:

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
      - phpMyAdmin
    ports:
      - 8080:80
    networks:
      - dbTestNet
    volumes:
      - ./:/var/www/html
    env_file:
      - ./configuration/wordpress.env

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    networks:
      - dbTestNet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./configuration/mysql.env

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    networks:
      - dbTestNet
    ports:
      - "80:80"
    env_file:
      - ./configuration/phpmyadmin.env

volumes:
  db_data:
